name: Build for OpenWrt ARMv7 (musl)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: armv7-unknown-linux-musleabihf

      - name: Build
        run: cargo build --release --target armv7-unknown-linux-musleabihf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mhrv-armv7-openwrt
          path: target/armv7-unknown-linux-musleabihf/release/mhrv
